---
title: "Irrigation Water Quality Tests - Interpretation and Recommendations"
author: Bryan Rutter and Dorivar Ruiz Diaz – Kansas State University Soil Testing
  Lab
output:
  github_document:
    toc: true
    toc_depth: 2
    pandoc_args: --webtex
bibliography: IrrRecs_RefLib.bib
link-citations: yes
---

# Background

Saline and sodic soils typically occur in areas where evapotranspiration rates exceed precipitation rates, or where irrigation water quality is marginal. The quality of irrigation water is largely a function of dissolved salt content, where waters with a higher salt content are of lower quality than those with a lower salt content. The type of dissolved salts is also important to consider. Dissolve sodium (Na) is of particular concern, as it can cause sodic soil conditions (e.g. disperion of clay and organic matter).

The salt content of soils and water can be evaluated by measuring their electrical conductivity (EC). For soils, this measurement is best taken from the filtrate of a soil saturated paste extraction. For water, the measurement can simply be performed on a sample of the irrigation water in question. The use of proper sampling methods and laboratory protocols is crucial for the interpretation of subsequent measurements, but is not discussed here.

# Objective

The goal of this project is to create an R script that automates some calculations that are useful for those who are managing irrigation systems for the production of agricultural crops, lawns, and gardeners.

# Description of calculated values

The calculated values are: _sodium adsorption ratio (SAR)_, _potential salt load (PSL)_, and _leaching requirement (LR)_.

## Sodium Adsorption Ratio

The sodium adsorption ratio (SAR) relates the concentration of sodium ions (Na^+^) to the concentrations of calcium (Ca^2+^) and magnesium (Mg^2+^) ions. These concentrations should be expressed in terms of cmol(+) kg^-1^ prior to calculation. Note that the concentration of cations in soils are often expressed in terms of mEq 100 g^-1^, which is equivalent to cmol(+) kg^-1^.

$$
\text{SAR} = \frac{[\text{Na}^+]}{\sqrt{\frac{[\text{Ca}^{2+}]+[\text{Mg}^{2+}]}{2}}}
$$
This SAR value is useful for determining whether a particular water is likely to induce sodicity, but can also be used to evaluate the current sodicity of a soil when determined from a saturated paste extract. Dispersion of clay and organic matter particles is likely if SAR > 13.

## Potential Salt Load

The total dissolved salts (TDS) in irrigation water can be estimated from EC of a water sample.

$$
\text{TDS (mg/L)} = \text{EC} \times 640\ ;\ \ \text{EC} \leq 5\ \text{mS cm}^{-1}
$$

$$
\text{TDS (mg/L)} = \text{EC} \times 800\ ;\ \ \text{EC} > 5\ \text{mS cm}^{-1}
$$

The potential salt load (PSL) can then be calculated from the TDS, and reported in terms of lbs of salt per acre-inch of water applied. This value represents the maximum amount of salt that would be added to the soil assuming no leaching occurs.

$$
\text{PSL (lbs/ac-inch)} = \text{TDS (mg/L)} \times 0.226
$$

## Leaching Requirement

Note: A more comprehensive discussion of leaching fraction (LF), leaching requirement (LR), and comparisons of various models used to estimate LR can be found in @Corwin2011. A brief description of these terms has been provided below, and is largely drawn from their paper.

Leaching fraction (LF) is defined as the fraction of applied irrigation water that moves beyond the plant root-zone, and represents the level of drainage and leaching of salts. As LF increases, the level of salt accumulation in the root-zone of a soil decreases. The leaching requirement (LR) represents the lowest LF that could be allowed without soil salinity becoming excessive and preventing optimal plant growth and crop yield. The calculation of LR requires, at minimum, knowledge of the salinity of the irrigation water to be applied to a crop, as well as the maximum soil EC that still allows for optimum yield of the crop to be grown.

Numerous models have been employed for the estimation of LR. Due to its simplicity, we use the Rhoades LR model here, also referred to as the Traditional LR Model [@Corwin2011].

$$
\text{LR} = \frac{\text{EC}_{\text{irr}}}{5\text{EC}^*_{\text{soil}}-\text{EC}_{\text{irr}}}
$$
Where:  
LR = leaching requirement (dim)  
EC~irr~ = EC measurement of irrigation water sample (mS cm^-1^)  
EC^\*^~soil~ = the maximum soil EC that still allows for optimum yield of the crop to be grown

**Important Notes:**

- LR is a maintenace leaching and is **NOT** the fraction of irrigation water required to remediate a saline, sodic, or saline-sodic soil.
- LR should be calculated based on the least salt-tolerant crop in a crop-rotation. For example, if a crop rotation consists of corn-wheat-soybean, the LR should be calculated based on the salt tolerance of soybean (~1.5 mS cm^-1^)
- For recommendations on the managment and remediation of saline, sodic, and saline-sodic soils, see @RuizDiaz2017

# References